package com.classroomhub.domain.attendance.entity;

import jakarta.persistence.*;
import lombok.*;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.Instant;
import java.time.LocalDate;
import java.util.UUID;

@Entity
@Table(name = "attendance_sessions")
@EntityListeners(AuditingEntityListener.class)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class AttendanceSession {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    @Column(name = "classroom_id", nullable = false)
    private UUID classroomId;

    @Column(name = "created_by", nullable = false)
    private UUID createdBy;

    @Column(nullable = false)
    private String title;

    @Column(length = 1000)
    private String description;

    @Column(nullable = false)
    @Enumerated(EnumType.STRING)
    @Builder.Default
    private Status status = Status.OPEN;

    /** Which subject the session covers (auto-generated sessions only). */
    @Column(name = "subject_id")
    private UUID subjectId;

    /** Period number (1..N) within the school day. */
    @Column(name = "period_number")
    private Integer periodNumber;

    /** Calendar date the session belongs to. */
    @Column(name = "session_date")
    private LocalDate sessionDate;

    /** Period start time as a timestamp; used by the UI to render countdowns. */
    @Column(name = "starts_at")
    private Instant startsAt;

    /** When null, the session never auto-closes. */
    @Column(name = "closes_at")
    private Instant closesAt;

    /** True if generated by the system from the timetable, false for manual sessions. */
    @Column(name = "auto_generated", nullable = false)
    @Builder.Default
    private boolean autoGenerated = false;

    @CreatedDate
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @LastModifiedDate
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    public enum Status { SCHEDULED, OPEN, CLOSED }
}
