package com.classroomhub.domain.attendance.service;

import com.classroomhub.common.exception.BusinessException;
import com.classroomhub.common.exception.ErrorCode;
import com.classroomhub.domain.attendance.PeriodTimes;
import com.classroomhub.domain.attendance.dto.*;
import com.classroomhub.domain.attendance.entity.AttendanceRecord;
import com.classroomhub.domain.attendance.entity.AttendanceSession;
import com.classroomhub.domain.attendance.repository.AttendanceRecordRepository;
import com.classroomhub.domain.attendance.repository.AttendanceSessionRepository;
import com.classroomhub.domain.auth.entity.User;
import com.classroomhub.domain.auth.repository.UserRepository;
import com.classroomhub.domain.classroom.entity.ClassroomMember;
import com.classroomhub.domain.classroom.repository.ClassroomMemberRepository;
import com.classroomhub.domain.classroom.service.ClassroomService;
import com.classroomhub.domain.notification.entity.Notification;
import com.classroomhub.domain.notification.service.NotificationService;
import com.classroomhub.domain.timetable.entity.Subject;
import com.classroomhub.domain.timetable.entity.TimetableEntry;
import com.classroomhub.domain.timetable.repository.SubjectRepository;
import com.classroomhub.domain.timetable.repository.TimetableEntryRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.scheduling.annotation.Async;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.*;
import java.util.*;
import java.util.function.Function;
import java.util.stream.Collectors;

@Slf4j
@Service
@RequiredArgsConstructor
public class AttendanceService {

    private static final ZoneId VN_ZONE = ZoneId.of("Asia/Ho_Chi_Minh");

    private final AttendanceSessionRepository sessionRepository;
    private final AttendanceRecordRepository recordRepository;
    private final ClassroomMemberRepository classroomMemberRepository;
    private final ClassroomService classroomService;
    private final UserRepository userRepository;
    private final NotificationService notificationService;
    private final TimetableEntryRepository timetableEntryRepository;
    private final SubjectRepository subjectRepository;

    @Value("${classroomhub.academic.year:2024-2025}")
    private String defaultAcademicYear;

    @Value("${classroomhub.academic.semester:1}")
    private int defaultSemester;

    // ─── Sessions ───────────────────────────────────────────────────────────────

    /**
     * Manual session creation kept as a teacher fallback when the auto-generator
     * misses a period (e.g. timetable not configured, system outage, ad-hoc roll call).
     */
    @Transactional
    public SessionResponse createSession(UUID classroomId, UUID requesterId, CreateSessionRequest req) {
        classroomService.requireRoleAtLeast(classroomId, requesterId, ClassroomMember.Role.TEACHER);

        AttendanceSession session = AttendanceSession.builder()
                .classroomId(classroomId)
                .createdBy(requesterId)
                .title(req.title())
                .description(req.description())
                .closesAt(req.closesAt())
                .autoGenerated(false)
                .build();
        sessionRepository.save(session);

        prepopulateRecords(classroomId, session.getId());

        // Notify only on manual creation; auto-generated sessions are silent
        // (one notification per period would be too noisy).
        recordRepository.findAllBySessionId(session.getId()).forEach(record ->
                notificationService.send(
                        record.getUserId(), classroomId,
                        Notification.Type.ATTENDANCE_PENDING,
                        "Điểm danh mới",
                        "Giáo viên đã mở phiên điểm danh" + (req.title() != null ? ": " + req.title() : ""),
                        session.getId()
                )
        );

        return SessionResponse.from(session, recordRepository.findAllBySessionId(session.getId()));
    }

    /**
     * For each period in today's timetable that doesn't already have a session,
     * create one. Idempotent — calling repeatedly is safe.
     *
     * @param sessionDate which day to generate; usually today
     */
    @Transactional
    public List<SessionResponse> generateSessionsForDate(UUID classroomId, UUID requesterId, LocalDate sessionDate) {
        classroomService.requireMember(classroomId, requesterId);
        return doGenerateSessionsForDate(classroomId, requesterId, sessionDate);
    }

    private List<SessionResponse> doGenerateSessionsForDate(UUID classroomId, UUID requesterId, LocalDate sessionDate) {
        TimetableEntry.DayOfWeek dow = toDow(sessionDate.getDayOfWeek());

        // Query by classroom + dayOfWeek without academic year filter so the fallback
        // works regardless of which year the timetable was generated for.
        List<TimetableEntry> entries = timetableEntryRepository
                .findByClassroomIdAndDayOfWeek(classroomId, dow)
                .stream()
                .sorted(Comparator.comparingInt(TimetableEntry::getPeriod))
                .toList();

        if (entries.isEmpty()) return List.of();

        List<UUID> subjectIds = entries.stream().map(TimetableEntry::getSubjectId).distinct().toList();
        Map<UUID, Subject> subjects = subjectRepository.findAllById(subjectIds).stream()
                .collect(Collectors.toMap(Subject::getId, Function.identity()));

        for (TimetableEntry entry : entries) {
            if (sessionRepository.existsByClassroomIdAndSessionDateAndPeriodNumber(
                    classroomId, sessionDate, entry.getPeriod())) {
                continue;
            }
            PeriodTimes.Slot slot = PeriodTimes.of(entry.getPeriod());
            Instant startsAt = ZonedDateTime.of(sessionDate, slot.start(), VN_ZONE).toInstant();
            Instant closesAt = startsAt.plusSeconds(30 * 60);
            Subject subject = subjects.get(entry.getSubjectId());
            String subjectName = subject != null ? subject.getName() : "Tiết " + entry.getPeriod();

            Instant now = Instant.now();
            AttendanceSession.Status initialStatus = startsAt.isAfter(now)
                    ? AttendanceSession.Status.SCHEDULED
                    : AttendanceSession.Status.OPEN;

            AttendanceSession session = AttendanceSession.builder()
                    .classroomId(classroomId)
                    .createdBy(requesterId)
                    .title(subjectName + " · Tiết " + entry.getPeriod())
                    .description(null)
                    .subjectId(entry.getSubjectId())
                    .periodNumber(entry.getPeriod())
                    .sessionDate(sessionDate)
                    .startsAt(startsAt)
                    .closesAt(closesAt)
                    .status(initialStatus)
                    .autoGenerated(true)
                    .build();
            sessionRepository.save(session);
            prepopulateRecords(classroomId, session.getId());
        }

        return listSessionsForDate(classroomId, sessionDate);
    }

    @Transactional
    public List<SessionResponse> listSessionsForDate(UUID classroomId, LocalDate sessionDate) {
        // Side-effect: any session that has already passed its closesAt is
        // moved to CLOSED so the UI doesn't accept late check-ins.
        autoCloseExpired(classroomId);

        List<AttendanceSession> sessions = sessionRepository
                .findAllByClassroomIdAndSessionDateOrderByPeriodNumberAsc(classroomId, sessionDate);
        if (sessions.isEmpty()) return List.of();

        Map<UUID, Subject> subjects = subjectRepository.findAllById(
                        sessions.stream()
                                .map(AttendanceSession::getSubjectId)
                                .filter(Objects::nonNull).distinct().toList()
                ).stream()
                .collect(Collectors.toMap(Subject::getId, Function.identity()));

        Map<UUID, List<AttendanceRecord>> recordsBySession = recordRepository
                .findAllBySessionIdIn(sessions.stream().map(AttendanceSession::getId).toList()).stream()
                .collect(Collectors.groupingBy(AttendanceRecord::getSessionId));

        return sessions.stream()
                .map(s -> SessionResponse.from(
                        s,
                        recordsBySession.getOrDefault(s.getId(), List.of()),
                        s.getSubjectId() != null && subjects.get(s.getSubjectId()) != null
                                ? subjects.get(s.getSubjectId()).getName()
                                : null))
                .toList();
    }

    private void autoCloseExpired(UUID classroomId) {
        Instant now = Instant.now();
        List<AttendanceSession> expired = sessionRepository
                .findAllByStatusAndClosesAtBefore(AttendanceSession.Status.OPEN, now);
        for (AttendanceSession s : expired) {
            if (!s.getClassroomId().equals(classroomId)) continue;
            s.setStatus(AttendanceSession.Status.CLOSED);
        }
        if (!expired.isEmpty()) sessionRepository.saveAll(expired);
    }

    /** Cron-driven safety net: close any expired session, system-wide. */
    @Scheduled(fixedDelay = 300_000)
    @Transactional
    public void autoCloseExpiredAll() {
        Instant now = Instant.now();
        List<AttendanceSession> expired = sessionRepository
                .findAllByStatusAndClosesAtBefore(AttendanceSession.Status.OPEN, now);
        for (AttendanceSession s : expired) s.setStatus(AttendanceSession.Status.CLOSED);
        if (!expired.isEmpty()) sessionRepository.saveAll(expired);
    }

    /** Every minute: open SCHEDULED sessions whose period has started. */
    @Scheduled(fixedDelay = 300_000)
    @Transactional
    public void autoOpenScheduledSessions() {
        Instant now = Instant.now();
        List<AttendanceSession> toOpen = sessionRepository
                .findAllByStatusAndStartsAtLessThanEqual(AttendanceSession.Status.SCHEDULED, now);
        for (AttendanceSession s : toOpen) s.setStatus(AttendanceSession.Status.OPEN);
        if (!toOpen.isEmpty()) sessionRepository.saveAll(toOpen);
    }

    /**
     * Pre-generate attendance sessions for the given timetable entries over the next
     * {@code daysAhead} days. Runs synchronously so sessions exist before the API response
     * returns, guaranteeing the attendance page shows them immediately.
     * Batches all saves to minimise DB round-trips.
     */
    @Transactional
    public void preGenerateSessionsFromEntries(List<TimetableEntry> entries, UUID requesterId, int daysAhead) {
        if (entries.isEmpty()) return;

        Map<UUID, Subject> subjectMap = subjectRepository.findAllById(
                entries.stream().map(TimetableEntry::getSubjectId).distinct().toList()
        ).stream().collect(Collectors.toMap(Subject::getId, Function.identity()));

        LocalDate today = LocalDate.now(VN_ZONE);
        Instant now = Instant.now();
        List<AttendanceSession> sessionsToSave = new ArrayList<>();

        for (int i = 0; i < daysAhead; i++) {
            LocalDate date = today.plusDays(i);
            if (date.getDayOfWeek() == java.time.DayOfWeek.SUNDAY) continue;
            TimetableEntry.DayOfWeek dow = toDow(date.getDayOfWeek());

            for (TimetableEntry entry : entries) {
                if (entry.getDayOfWeek() != dow) continue;
                if (sessionRepository.existsByClassroomIdAndSessionDateAndPeriodNumber(
                        entry.getClassroomId(), date, entry.getPeriod())) continue;

                PeriodTimes.Slot slot = PeriodTimes.of(entry.getPeriod());
                Instant startsAt = ZonedDateTime.of(date, slot.start(), VN_ZONE).toInstant();
                Instant closesAt = startsAt.plusSeconds(30 * 60);
                Subject subject = subjectMap.get(entry.getSubjectId());
                String subjectName = subject != null ? subject.getName() : "Tiết " + entry.getPeriod();
                AttendanceSession.Status status = startsAt.isAfter(now)
                        ? AttendanceSession.Status.SCHEDULED
                        : AttendanceSession.Status.OPEN;

                sessionsToSave.add(AttendanceSession.builder()
                        .classroomId(entry.getClassroomId())
                        .createdBy(requesterId)
                        .title(subjectName + " · Tiết " + entry.getPeriod())
                        .subjectId(entry.getSubjectId())
                        .periodNumber(entry.getPeriod())
                        .sessionDate(date)
                        .startsAt(startsAt)
                        .closesAt(closesAt)
                        .status(status)
                        .autoGenerated(true)
                        .build());
            }
        }

        if (sessionsToSave.isEmpty()) return;

        List<AttendanceSession> saved = sessionRepository.saveAll(sessionsToSave);

        // Batch-prepopulate records for all new sessions
        List<AttendanceRecord> allRecords = new ArrayList<>();
        for (AttendanceSession session : saved) {
            classroomMemberRepository.findAllByClassroomId(session.getClassroomId()).stream()
                    .filter(m -> m.getRole() != com.classroomhub.domain.classroom.entity.ClassroomMember.Role.OWNER
                              && m.getRole() != com.classroomhub.domain.classroom.entity.ClassroomMember.Role.TEACHER)
                    .map(m -> AttendanceRecord.builder()
                            .sessionId(session.getId())
                            .classroomId(session.getClassroomId())
                            .userId(m.getUserId())
                            .status(AttendanceRecord.Status.ABSENT)
                            .build())
                    .forEach(allRecords::add);
        }
        if (!allRecords.isEmpty()) recordRepository.saveAll(allRecords);

        log.info("preGenerateSessionsFromEntries: created {} sessions over {} days", saved.size(), daysAhead);
    }

    /** Every night at midnight: generate sessions for the next 14 days for all classrooms. */
    @Scheduled(cron = "0 0 0 * * *", zone = "Asia/Ho_Chi_Minh")
    @Transactional
    public void dailyPreGenerateSessions() {
        UUID systemUserId = userRepository.findFirstByUserType(com.classroomhub.domain.auth.entity.User.UserType.SYSTEM_ADMIN)
                .map(u -> u.getId()).orElse(null);
        if (systemUserId == null) {
            log.warn("dailyPreGenerateSessions: no SYSTEM_ADMIN found, skipping");
            return;
        }
        List<UUID> classroomIds = timetableEntryRepository.findAllDistinctClassroomIds();
        if (classroomIds.isEmpty()) return;

        LocalDate today = LocalDate.now(VN_ZONE);
        for (UUID classroomId : classroomIds) {
            for (int i = 0; i < 14; i++) {
                LocalDate date = today.plusDays(i);
                if (date.getDayOfWeek() == java.time.DayOfWeek.SUNDAY) continue;
                try {
                    doGenerateSessionsForDate(classroomId, systemUserId, date);
                } catch (Exception ex) {
                    log.warn("dailyPreGenerateSessions failed for classroom {} on {}: {}",
                            classroomId, date, ex.getMessage());
                }
            }
        }
        log.info("dailyPreGenerateSessions: pre-generated sessions for {} classrooms", classroomIds.size());
    }

    @Transactional(readOnly = true)
    public Page<SessionResponse> listSessions(UUID classroomId, UUID requesterId, Pageable pageable) {
        classroomService.requireMember(classroomId, requesterId);
        return sessionRepository.findAllByClassroomIdOrderByCreatedAtDesc(classroomId, pageable)
                .map(s -> SessionResponse.from(
                        s,
                        recordRepository.findAllBySessionId(s.getId()),
                        s.getSubjectId() != null
                                ? subjectRepository.findById(s.getSubjectId()).map(Subject::getName).orElse(null)
                                : null));
    }

    @Transactional(readOnly = true)
    public SessionResponse getSession(UUID classroomId, UUID sessionId, UUID requesterId) {
        classroomService.requireMember(classroomId, requesterId);
        AttendanceSession session = requireSession(sessionId, classroomId);
        List<AttendanceRecord> records = recordRepository.findAllBySessionId(sessionId);
        String subjectName = session.getSubjectId() != null
                ? subjectRepository.findById(session.getSubjectId()).map(Subject::getName).orElse(null)
                : null;
        return SessionResponse.from(session, records, subjectName);
    }

    @Transactional
    public void deleteSession(UUID classroomId, UUID sessionId, UUID requesterId) {
        classroomService.requireRoleAtLeast(classroomId, requesterId, ClassroomMember.Role.TEACHER);
        AttendanceSession session = requireSession(sessionId, classroomId);
        // Delete records first (no cascade defined on the FK).
        recordRepository.deleteAll(recordRepository.findAllBySessionId(sessionId));
        sessionRepository.delete(session);
    }

    @Transactional
    public SessionResponse closeSession(UUID classroomId, UUID sessionId, UUID requesterId) {
        classroomService.requireRoleAtLeast(classroomId, requesterId, ClassroomMember.Role.TEACHER);
        AttendanceSession session = requireSession(sessionId, classroomId);
        session.setStatus(AttendanceSession.Status.CLOSED);
        sessionRepository.save(session);
        return SessionResponse.from(session, recordRepository.findAllBySessionId(sessionId));
    }

    // ─── Student self check-in ──────────────────────────────────────────────────

    /**
     * Student records their own attendance. Disallowed once the session is closed.
     * If the student is checking in after the period started they are marked LATE
     * (15-minute grace), otherwise PRESENT.
     */
    @Transactional
    public RecordResponse checkIn(UUID classroomId, UUID sessionId, UUID userId, CheckInRequest req) {
        classroomService.requireMember(classroomId, userId);
        AttendanceSession session = requireSession(sessionId, classroomId);
        if (session.getStatus() == AttendanceSession.Status.SCHEDULED) {
            // Auto-open on first check-in attempt if the period has already started.
            if (session.getStartsAt() != null && !Instant.now().isBefore(session.getStartsAt())) {
                session.setStatus(AttendanceSession.Status.OPEN);
                sessionRepository.save(session);
            } else {
                throw new BusinessException(ErrorCode.SESSION_NOT_STARTED);
            }
        }
        if (session.getStatus() == AttendanceSession.Status.CLOSED) {
            throw new BusinessException(ErrorCode.SESSION_CLOSED);
        }
        if (session.getClosesAt() != null && Instant.now().isAfter(session.getClosesAt())) {
            session.setStatus(AttendanceSession.Status.CLOSED);
            sessionRepository.save(session);
            throw new BusinessException(ErrorCode.SESSION_CLOSED);
        }

        AttendanceRecord record = recordRepository.findBySessionIdAndUserId(sessionId, userId)
                .orElseGet(() -> AttendanceRecord.builder()
                        .sessionId(sessionId)
                        .classroomId(classroomId)
                        .userId(userId)
                        .build());

        // PRESENT unless the student arrived more than 15 minutes after period start.
        AttendanceRecord.Status status = AttendanceRecord.Status.PRESENT;
        if (session.getStartsAt() != null
                && Instant.now().isAfter(session.getStartsAt().plusSeconds(15 * 60))) {
            status = AttendanceRecord.Status.LATE;
        }
        record.setStatus(status);
        if (req != null && req.note() != null && !req.note().isBlank()) {
            record.setNote(req.note());
        }
        record.setReviewedBy(userId);
        record.setReviewedAt(Instant.now());
        recordRepository.save(record);

        User u = userRepository.findById(userId).orElse(null);
        return RecordResponse.from(record,
                u != null ? u.getDisplayName() : "",
                u != null ? u.getAvatarUrl() : null);
    }

    // ─── Mark attendance ─────────────────────────────────────────────────────────

    @Transactional
    public RecordResponse markAttendance(UUID classroomId, UUID sessionId, UUID recordId,
                                         UUID teacherId, MarkAttendanceRequest req) {
        classroomService.requireRoleAtLeast(classroomId, teacherId, ClassroomMember.Role.TEACHER);

        AttendanceRecord record = recordRepository.findById(recordId)
                .filter(r -> r.getSessionId().equals(sessionId) && r.getClassroomId().equals(classroomId))
                .orElseThrow(() -> new BusinessException(ErrorCode.RECORD_NOT_FOUND));

        record.setStatus(req.status());
        if (req.note() != null) record.setNote(req.note().isBlank() ? null : req.note());
        record.setReviewedBy(teacherId);
        record.setReviewedAt(Instant.now());
        recordRepository.save(record);

        User user = userRepository.findById(record.getUserId()).orElse(null);
        return RecordResponse.from(record,
                user != null ? user.getDisplayName() : "",
                user != null ? user.getAvatarUrl() : null);
    }

    // ─── Records list ────────────────────────────────────────────────────────────

    @Transactional(readOnly = true)
    public List<RecordResponse> listRecords(UUID classroomId, UUID sessionId, UUID requesterId) {
        classroomService.requireMember(classroomId, requesterId);
        requireSession(sessionId, classroomId);

        List<AttendanceRecord> records = recordRepository.findAllBySessionId(sessionId);
        List<UUID> userIds = records.stream().map(AttendanceRecord::getUserId).toList();
        Map<UUID, User> users = userRepository.findAllById(userIds).stream()
                .collect(Collectors.toMap(User::getId, Function.identity()));

        return records.stream()
                .sorted(Comparator.comparing(r -> {
                    User u = users.get(r.getUserId());
                    return u != null ? u.getDisplayName() : "";
                }))
                .map(r -> {
                    User u = users.get(r.getUserId());
                    return RecordResponse.from(r,
                            u != null ? u.getDisplayName() : "",
                            u != null ? u.getAvatarUrl() : null);
                })
                .toList();
    }

    // ─── Helpers ─────────────────────────────────────────────────────────────────

    private void prepopulateRecords(UUID classroomId, UUID sessionId) {
        List<ClassroomMember> members = classroomMemberRepository.findAllByClassroomId(classroomId);
        List<AttendanceRecord> records = members.stream()
                .filter(m -> m.getRole() != ClassroomMember.Role.OWNER
                          && m.getRole() != ClassroomMember.Role.TEACHER)
                .map(m -> AttendanceRecord.builder()
                        .sessionId(sessionId)
                        .classroomId(classroomId)
                        .userId(m.getUserId())
                        .status(AttendanceRecord.Status.ABSENT)
                        .build())
                .toList();
        recordRepository.saveAll(records);
    }

    private AttendanceSession requireSession(UUID sessionId, UUID classroomId) {
        return sessionRepository.findById(sessionId)
                .filter(s -> s.getClassroomId().equals(classroomId))
                .orElseThrow(() -> new BusinessException(ErrorCode.SESSION_NOT_FOUND));
    }

    private static TimetableEntry.DayOfWeek toDow(java.time.DayOfWeek d) {
        return switch (d) {
            case MONDAY    -> TimetableEntry.DayOfWeek.MONDAY;
            case TUESDAY   -> TimetableEntry.DayOfWeek.TUESDAY;
            case WEDNESDAY -> TimetableEntry.DayOfWeek.WEDNESDAY;
            case THURSDAY  -> TimetableEntry.DayOfWeek.THURSDAY;
            case FRIDAY    -> TimetableEntry.DayOfWeek.FRIDAY;
            case SATURDAY  -> TimetableEntry.DayOfWeek.SATURDAY;
            case SUNDAY    -> TimetableEntry.DayOfWeek.SUNDAY;
        };
    }
}
