export type SessionStatus = 'SCHEDULED' | 'OPEN' | 'CLOSED';
export type RecordStatus = 'PRESENT' | 'ABSENT' | 'LATE' | 'EXCUSED';

export interface AttendanceSession {
  id: string;
  classroomId: string;
  createdBy: string;
  title: string;
  description: string | null;
  status: SessionStatus;
  subjectId: string | null;
  subjectName: string | null;
  periodNumber: number | null;
  sessionDate: string | null;
  startsAt: string | null;
  closesAt: string | null;
  autoGenerated: boolean;
  totalRecords: number;
  presentCount: number;
  absentCount: number;
  lateCount: number;
  excusedCount: number;
  createdAt: string;
}

export interface AttendanceRecord {
  id: string;
  sessionId: string;
  userId: string;
  displayName: string;
  avatarUrl: string | null;
  status: RecordStatus;
  note: string | null;
  reviewedBy: string | null;
  reviewedAt: string | null;
  checkedInAt: string;
}

export const RECORD_STATUS_LABELS: Record<RecordStatus, string> = {
  PRESENT: 'Có mặt',
  ABSENT:  'Vắng',
  LATE:    'Đi muộn',
  EXCUSED: 'Có phép',
};

export const RECORD_STATUS_VARIANT: Record<RecordStatus, 'green' | 'red' | 'blue' | 'amber'> = {
  PRESENT: 'green',
  ABSENT:  'red',
  LATE:    'blue',
  EXCUSED: 'amber',
};

/**
 * VN school period schedule (matches backend's PeriodTimes). Used purely
 * for client-side rendering of "Tiết X · 07:00 – 07:45" labels.
 */
export const PERIOD_TIMES: Record<number, { start: string; end: string }> = {
  1:  { start: '07:00', end: '07:45' },
  2:  { start: '07:55', end: '08:40' },
  3:  { start: '08:50', end: '09:35' },
  4:  { start: '09:55', end: '10:40' },
  5:  { start: '10:50', end: '11:35' },
  6:  { start: '13:30', end: '14:15' },
  7:  { start: '14:25', end: '15:10' },
  8:  { start: '15:30', end: '16:15' },
  9:  { start: '16:25', end: '17:10' },
  10: { start: '17:20', end: '18:05' },
};
