spring.application.name=backend

spring.datasource.url=${SUPABASE_URL}
spring.datasource.username=${SUPABASE_USERNAME}
spring.datasource.password=${SUPABASE_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

server.address=0.0.0.0

jwt.signer-key=${JWT_SIGNER_KEY}

mezon.client-id=${MEZON_CLIENT_ID}
mezon.client-secret=${MEZON_CLIENT_SECRET}
mezon.redirect-uri=${MEZON_REDIRECT_URI}
mezon.auth-url=${MEZON_AUTH_URL}
mezon.token-url=${MEZON_TOKEN_URL}
mezon.user-info-url=${MEZON_USER_INFO_URL}