package com.classroomhub.domain.attendance.dto;

import com.classroomhub.domain.attendance.entity.AttendanceRecord;
import com.classroomhub.domain.attendance.entity.AttendanceSession;

import java.time.Instant;
import java.time.LocalDate;
import java.util.List;
import java.util.UUID;

public record SessionResponse(
        UUID id,
        UUID classroomId,
        UUID createdBy,
        String title,
        String description,
        AttendanceSession.Status status,
        UUID subjectId,
        String subjectName,
        Integer periodNumber,
        LocalDate sessionDate,
        Instant startsAt,
        Instant closesAt,
        boolean autoGenerated,
        int totalRecords,
        int presentCount,
        int absentCount,
        int lateCount,
        int excusedCount,
        Instant createdAt
) {
    public static SessionResponse from(AttendanceSession s, List<AttendanceRecord> records, String subjectName) {
        int present = count(records, AttendanceRecord.Status.PRESENT);
        int absent  = count(records, AttendanceRecord.Status.ABSENT);
        int late    = count(records, AttendanceRecord.Status.LATE);
        int excused = count(records, AttendanceRecord.Status.EXCUSED);
        return new SessionResponse(
                s.getId(), s.getClassroomId(), s.getCreatedBy(),
                s.getTitle(), s.getDescription(), s.getStatus(),
                s.getSubjectId(), subjectName,
                s.getPeriodNumber(), s.getSessionDate(),
                s.getStartsAt(), s.getClosesAt(), s.isAutoGenerated(),
                records.size(), present, absent, late, excused,
                s.getCreatedAt()
        );
    }

    public static SessionResponse from(AttendanceSession s, List<AttendanceRecord> records) {
        return from(s, records, null);
    }

    private static int count(List<AttendanceRecord> records, AttendanceRecord.Status status) {
        return (int) records.stream().filter(r -> r.getStatus() == status).count();
    }
}
